
export const housesData = [
  {
    id: 1,
    type: 'Land',
    name: 'Plot 1',
    description:
      'A piece of land measuring 100 sq ft. 1 of almost a hundred units of secure land available for purchase. The survey has been carried out and the  Deed of Transfer will be issued on payment.',
    image: "https://i.imgur.com/XWWpde1.jpg",
    imageLg: "https://i.imgur.com/XWWpde1.jpg",
    city: 'Benin City',
    address: 'Okeze, Utekon, Ovia N.E 302117',
    surface: '100 sq ft',
    price: '1,600,000',
    agent: {
      image: "https://i.imgur.com/ToZMnh3.png",
      name: 'Oello Realtors',
      phone: '08137152040',
    },
  },
    {
    id: 2,
    type: 'Land',
    name: 'Plot 2',
    description:
      'A piece of land measuring 100 sq ft. 1 of almost a hundred units of secure land available for purchase. The survey has been carried out and the  Deed of Transfer will be issued on payment.',
    image: "https://i.imgur.com/RJH6vhO.jpg",
    imageLg: "https://i.imgur.com/RJH6vhO.jpg",
    city: 'Benin City',
    address: 'Okeze, Utekon, Ovia N.E 302117',
    surface: '100 sq ft',
    price: '1,600,000',
    agent: {
      image: "https://i.imgur.com/ToZMnh3.png",
      name: 'Oello Realtors',
      phone: '08137152040',
    },
  },
    {
    id: 3,
    type: 'Land',
    name: 'Plot 3',
    description:
      'A piece of land measuring 100 sq ft. 1 of almost a hundred units of secure land available for purchase. The survey has been carried out and the  Deed of Transfer will be issued on payment.',
    image: "https://i.imgur.com/rSbgl6r.jpg",
    imageLg: "https://i.imgur.com/rSbgl6r.jpg",
    city: 'Benin City',
    address: 'Okeze, Utekon, Ovia N.E 302117',
    surface: '100 sq ft',
    price: '1,600,000',
    agent: {
      image: "https://i.imgur.com/ToZMnh3.png",
      name: 'Oello Realtors',
      phone: '08137152040',
    },
  },
    {
    id: 4,
    type: 'Land',
    name: 'Plot 4',
    description:
      'A piece of land measuring 100 sq ft. 1 of almost a hundred units of secure land available for purchase. The survey has been carried out and the  Deed of Transfer will be issued on payment.',
    image: "https://i.imgur.com/34NUHIZ.jpg",
    imageLg: "https://i.imgur.com/34NUHIZ.jpg",
    city: 'Benin City',
    address: 'Okeze, Utekon, Ovia N.E 302117',
    surface: '100 sq ft',
    price: '1,600,000',
    agent: {
      image: "https://i.imgur.com/ToZMnh3.png",
      name: 'Oello Realtors',
      phone: '08137152040',
    },
  },
    {
    id: 5,
    type: 'Land',
    name: 'Plot 5',
    description:
      'A piece of land measuring 100 sq ft. 1 of almost a hundred units of secure land available for purchase. The survey has been carried out and the  Deed of Transfer will be issued on payment.',
    image: "https://i.imgur.com/TUsoFG8.jpg",
    imageLg: "https://i.imgur.com/TUsoFG8.jpg",
    city: 'Benin City',
    address: 'Okeze, Utekon, Ovia N.E 302117',
    surface: '100 sq ft',
    price: '1,600,000',
    agent: {
      image: "https://i.imgur.com/ToZMnh3.png",
      name: 'Oello Realtors',
      phone: '08137152040',
    },
  },
    {
    id: 6,
    type: 'Land',
    name: 'Plot 6',
    description:
      'A piece of land measuring 100 sq ft. 1 of almost a hundred units of secure land available for purchase. The survey has been carried out and the  Deed of Transfer will be issued on payment.',
    image: "https://i.imgur.com/dQrsFNj.jpg",
    imageLg: "https://i.imgur.com/dQrsFNj.jpg",
    city: 'Benin City',
    address: 'Okeze, Utekon, Ovia N.E 302117',
    surface: '100 sq ft',
    price: '1,600,000',
    agent: {
      image: "https://i.imgur.com/ToZMnh3.png",
      name: 'Oello Realtors',
      phone: '08137152040',
    },
  },
    {
    id: 7,
    type: 'Land',
    name: 'Plot 7',
    description:
      'A piece of land measuring 100 sq ft. 1 of almost a hundred units of secure land available for purchase. The survey has been carried out and the  Deed of Transfer will be issued on payment.',
    image: "https://i.imgur.com/fVHrqxY.jpg",
    imageLg: "https://i.imgur.com/fVHrqxY.jpg",
    city: 'Benin City',
    address: 'Okeze, Utekon, Ovia N.E 302117',
    surface: '100 sq ft',
    price: '1,600,000',
    agent: {
      image: "https://i.imgur.com/ToZMnh3.png",
      name: 'Oello Realtors',
      phone: '08137152040',
    },
  },
    {
    id: 8,
    type: 'Land',
    name: 'Plot 8',
    description:
      'A piece of land measuring 100 sq ft. 1 of almost a hundred units of secure land available for purchase. The survey has been carried out and the  Deed of Transfer will be issued on payment.',
    image: "https://i.imgur.com/Oxs3yri.jpg",
    imageLg: "https://i.imgur.com/Oxs3yri.jpg",
    city: 'Benin City',
    address: 'Okeze, Utekon, Ovia N.E 302117',
    surface: '100 sq ft',
    price: '1,600,000',
    agent: {
      image: "https://i.imgur.com/ToZMnh3.png",
      name: 'Oello Realtors',
      phone: '08137152040',
    },
  },
    {
    id: 9,
    type: 'Land',
    name: 'Plot 9',
    description:
      'A piece of land measuring 100 sq ft. 1 of almost a hundred units of secure land available for purchase. The survey has been carried out and the  Deed of Transfer will be issued on payment.',
    image: "https://i.imgur.com/f6VzBK1.jpg",
    imageLg: "https://i.imgur.com/f6VzBK1.jpg",
    city: 'Benin City',
    address: 'Okeze, Utekon, Ovia N.E 302117',
    surface: '100 sq ft',
    price: '1,600,000',
    agent: {
      image: "https://i.imgur.com/ToZMnh3.png",
      name: 'Oello Realtors',
      phone: '08137152040',
    },
  },
    {
    id: 10,
    type: 'Land',
    name: 'Plot 10',
    description:
      'A piece of land measuring 100 sq ft. 1 of almost a hundred units of secure land available for purchase. The survey has been carried out and the  Deed of Transfer will be issued on payment.',
    image: "https://i.imgur.com/9XYR7Ch.jpg",
    imageLg: "https://i.imgur.com/9XYR7Ch.jpg",
    city: 'Benin City',
    address: 'Okeze, Utekon, Ovia N.E 302117',
    surface: '100 sq ft',
    price: '1,600,000',
    agent: {
      image: "https://i.imgur.com/ToZMnh3.png",
      name: 'Oello Realtors',
      phone: '08137152040',
    },
  },
    {
    id: 11,
    type: 'Land',
    name: 'Plot 11',
    description:
      'A piece of land measuring 100 sq ft. 1 of almost a hundred units of secure land available for purchase. The survey has been carried out and the  Deed of Transfer will be issued on payment.',
    image: "https://i.imgur.com/6Y3uKsG.jpg",
    imageLg: "https://i.imgur.com/6Y3uKsG.jpg",
    city: 'Benin City',
    address: 'Okeze, Utekon, Ovia N.E 302117',
    surface: '100 sq ft',
    price: '1,600,000',
    agent: {
      image: "https://i.imgur.com/ToZMnh3.png",
      name: 'Oello Realtors',
      phone: '08137152040',
    },
  },
    {
    id: 12,
    type: 'Land',
    name: 'Plot 12',
    description:
      'A piece of land measuring 100 sq ft. 1 of almost a hundred units of secure land available for purchase. The survey has been carried out and the  Deed of Transfer will be issued on payment.',
    image: "https://i.imgur.com/cAqFSOK.jpg",
    imageLg: "https://i.imgur.com/cAqFSOK.jpg",
    city: 'Benin City',
    address: 'Okeze, Utekon, Ovia N.E 302117',
    surface: '100 sq ft',
    price: '1,600,000',
    agent: {
      image: "https://i.imgur.com/ToZMnh3.png",
      name: 'Oello Realtors',
      phone: '08137152040',
    },
  },
    {
    id: 13,
    type: 'Land',
    name: 'Plot 13',
    description:
      'A piece of land measuring 100 sq ft. 1 of almost a hundred units of secure land available for purchase. The survey has been carried out and the  Deed of Transfer will be issued on payment.',
    image: "https://i.imgur.com/SkQaAzV.jpg",
    imageLg: "https://i.imgur.com/SkQaAzV.jpg",
    city: 'Benin City',
    address: 'Okeze, Utekon, Ovia N.E 302117',
    surface: '100 sq ft',
    price: '1,600,000',
    agent: {
      image: "https://i.imgur.com/ToZMnh3.png",
      name: 'Oello Realtors',
      phone: '08137152040',
    },
  },
  {
    id: 14,
    type: 'Land',
    name: 'Plot 14',
    description:
      'A piece of land measuring 100 sq ft. 1 of almost a hundred units of secure land available for purchase. The survey has been carried out and the  Deed of Transfer will be issued on payment.',
    image: "https://i.imgur.com/aGHInZB.jpg",
    imageLg: "https://i.imgur.com/aGHInZB.jpg",
    city: 'Benin City',
    address: 'Okeze, Utekon, Ovia N.E 302117',
    surface: '100 sq ft',
    price: '1,600,000',
    agent: {
      image: "https://i.imgur.com/ToZMnh3.png",
      name: 'Oello Realtors',
      phone: '08137152040',
    },
  },
  {
    id: 15,
    type: 'Land',
    name: 'Plot 15',
    description:
      'A piece of land measuring 100 sq ft. 1 of almost a hundred units of secure land available for purchase. The survey has been carried out and the  Deed of Transfer will be issued on payment.',
    image: "https://i.imgur.com/gEuATEz.jpg",
    imageLg: "https://i.imgur.com/gEuATEz.jpg",
    city: 'Benin City',
    address: 'Okeze, Utekon, Ovia N.E 302117',
    surface: '100 sq ft',
    price: '1,600,000',
    agent: {
      image: "https://i.imgur.com/ToZMnh3.png",
      name: 'Oello Realtors',
      phone: '08137152040',
    },
  },
  {
    id: 16,
    type: 'Land',
    name: 'Plot 16',
    description:
      'A piece of land measuring 100 sq ft. 1 of almost a hundred units of secure land available for purchase. The survey has been carried out and the  Deed of Transfer will be issued on payment.',
    image: "https://i.imgur.com/65oHEnd.jpg",
    imageLg: "https://i.imgur.com/65oHEnd.jpg",
    city: 'Benin City',
    address: 'Okeze, Utekon, Ovia N.E 302117',
    surface: '100 sq ft',
    price: '1,600,000',
    agent: {
      image: "https://i.imgur.com/ToZMnh3.png",
      name: 'Oello Realtors',
      phone: '08137152040',
    },
  },
  {
    id: 17,
    type: 'Land',
    name: 'Plot 17',
    description:
      'A piece of land measuring 100 sq ft. 1 of almost a hundred units of secure land available for purchase. The survey has been carried out and the  Deed of Transfer will be issued on payment.',
    image: "https://i.imgur.com/kJg7Uyn.jpg",
    imageLg: "https://i.imgur.com/kJg7Uyn.jpg",
    city: 'Benin City',
    address: 'Okeze, Utekon, Ovia N.E 302117',
    surface: '100 sq ft',
    price: '1,600,000',
    agent: {
      image: "https://i.imgur.com/ToZMnh3.png",
      name: 'Oello Realtors',
      phone: '08137152040',
    },
  },
  {
    id: 18,
    type: 'Land',
    name: 'Plot 18',
    description:
      'A piece of land measuring 100 sq ft. 1 of almost a hundred units of secure land available for purchase. The survey has been carried out and the  Deed of Transfer will be issued on payment.',
    image: "https://i.imgur.com/JxaBQuA.jpg",
    imageLg: "https://i.imgur.com/JxaBQuA.jpg",
    city: 'Benin City',
    address: 'Okeze, Utekon, Ovia N.E 302117',
    surface: '100 sq ft',
    price: '1,600,000',
    agent: {
      image: "https://i.imgur.com/ToZMnh3.png",
      name: 'Oello Realtors',
      phone: '08137152040',
    },
  },
  {
    id: 19,
    type: 'Land',
    name: 'Plot 19',
    description:
      'A piece of land measuring 100 sq ft. 1 of almost a hundred units of secure land available for purchase. The survey has been carried out and the  Deed of Transfer will be issued on payment.',
    image: "https://i.imgur.com/W87GcZ9.jpg",
    imageLg: "https://i.imgur.com/W87GcZ9.jpg",
    city: 'Benin City',
    address: 'Okeze, Utekon, Ovia N.E 302117',
    surface: '100 sq ft',
    price: '1,600,000',
    agent: {
      image: "https://i.imgur.com/ToZMnh3.png",
      name: 'Oello Realtors',
      phone: '08137152040',
    },
  },
  {
    id: 20,
    type: 'Land',
    name: 'Plot 20',
    description:
      'A piece of land measuring 100 sq ft. 1 of almost a hundred units of secure land available for purchase. The survey has been carried out and the  Deed of Transfer will be issued on payment.',
    image: "https://i.imgur.com/fojiWHT.jpg",
    imageLg: "https://i.imgur.com/fojiWHT.jpg",
    city: 'Benin City',
    address: 'Okeze, Utekon, Ovia N.E 302117',
    surface: '100 sq ft',
    price: '1,600,000',
    agent: {
      image: "https://i.imgur.com/ToZMnh3.png",
      name: 'Oello Realtors',
      phone: '08137152040',
    },
  },
];
